Pull Request for Tanzu Packages Installation Doc
vmware-tanzu-labs/tanzu-validated-solutions pull request #153
Opened 2022-04-18 03:09 UTC by manishjha86

2022-04-27 09:45 UTC, MarilynHorn requested changes
Completed IX review of:
- tko-package-install.md
- tko-on-vsphere-with-tanzu
- index.md (minor edit)

2022-05-05 08:12 UTC, manishjha86 commented on src/reference-designs/tko-on-vsphere-with-tanzu.md
> +
Multus CNI provides pod networking only and is dependent on Antrea or calico. The section where antrea and calico is discussed is for tanzu Kubernetes cluster networking and is different than pod networking

2022-05-05 08:15 UTC, manishjha86 commented on src/reference-designs/tko-on-vsphere-with-tanzu.md
> +When you deploy a Tanzu Kubernetes cluster using Tanzu CLI using the default configuration, Antrea CNI is automatically enabled in the cluster.
> 

The right statement should be as follows:

When you deploy a Tanzu Kubernetes cluster using the default configuration by invoking Tanzu CLI, Antrea CNI is automatically enabled in the cluster.

2022-05-09 12:47 UTC, manishjha86 commented
Deleting this pull request as it has unwanted commits from other pull requests that was raised accidentally from my forked main repo

2022-05-09 12:47 UTC, closed without merging