Tanzu Edge Solutions Architecture - initial commit
vmware-tanzu-labs/tanzu-validated-solutions pull request #168
Opened 2022-04-26 12:29 UTC by bserratrice

Initial commit for the release of the Tanzu Edge Solutions Architecture.

2022-06-07 02:09 UTC, craigtracey commented
@bserratrice were you able to apply the changes I provided? Please reach out if you are having any issues.

2022-06-08 15:41 UTC, bserratrice commented
> @bserratrice were you able to apply the changes I provided? Please reach out if you are having any issues.

Changes have been applied. Please review.

2022-06-10 16:40 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +This solution architecture is intended for anyone responsible for designing, implementing, managing and securing edge locations, including DevOps admins, VI admins, platform operators, and security t
... managing, and securing ...

2022-06-10 16:46 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure: Edge Kubernetes Cluster fleet observability
Move into square brackets in line 842.

2022-06-10 16:49 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Tanzu Kubernetes Grid on top of the VMware Edge Compute stack provides an efficient way to deploy and manage Kubernetes infrastructure at the Edge at scale. Integrated with Tanzu Mission Control and
.... it allows enterprises to ... applications and features for ...

2022-06-10 16:54 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure: Harbor registry federated topology
Global: Please move Figure headings into the square brackets for the figure.

2022-06-10 16:57 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Table: Design Decisions
Move to line 432. Write as a lead, for example: The following table describes the justification and implication of the design decisions in the architecture.

2022-06-10 20:21 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Edge computing is gaining a lot of momentum for a variety of reasons that range from avoidance of latency, data volume, and bandwidth considerations to need for autonomous disconnected operation, pri
... to the need for autonomous ... operations, privacy, and ... Traditionally, these applications are ... run on VMs, ... but with

2022-06-10 20:21 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +For those companies that already have remote offices and branch offices with a few servers running edge workloads, running modern, distributed applications across your edge locations can add a new la
For companies ...

2022-06-10 20:25 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +The Tanzu Design for VMware Edge Compute Stack described here offers a best practice for running Tanzu at edge locations where the VMware Edge Compute Stack is already deployed. We’ll specifically ad
The Tanzu design ...deployed. We will specifically address the following challenges ...

2022-06-10 20:27 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +- Global Multi-cluster Management: VMware Tanzu Mission Control (TMC) is a centralized management platform for consistently operating and securing your Kubernetes infrastructure and modern applicatio
Global Multi-Cluster Management or Global multi-cluster management
Full-Stack Observability or Full-stack observability

2022-06-10 21:21 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +This solution guide is focused on the centralized model where a vCenter is deployed at the main datacenter location and a datacenter with vSphere cluster at each edge location. It is assumed that the
Replace lines 27 and 28 with the following - 
Multiple topologies are possible for edge deployments. Some of the topologies are described in this section. However, the VMware Tanzu Edge Solution Architecture uses a centralized or hub and spoke topology, where a vCenter is deployed at the main datacenter location and a vSphere cluster is deployed in the datacenter at each edge location. This design document assumes that the vSphere infrastructure is already deployed.

2022-06-10 21:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +In this topology, the management plane is entirely residing in the main datacenter. The centralized management plane composed of vCenter, NSX Advanced Load Balancer controller and TKG Management clus
... the management plane resides entirely in ... NSX Advanced Load Balancer Controller, and Tanzu Kubernetes Grid management cluster ...

2022-06-10 21:32 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Only the TKG Workload clusters are created at the edge along with Load Balancing components (Service Engines). This design provides a minimal footprint at the edge.
Only the Tanzu Kubernetes Grid workload clusters and the NSX Advanced Load Balancer Service Engines (SEs) are created at the edge.

2022-06-10 21:34 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Only the TKG Workload clusters are created at the edge along with Load Balancing components (Service Engines). This design provides a minimal footprint at the edge.
Global: Use expanded product names - Tanzu Kubernetes Grid, Tanzu Mission Control, NSX Advanced Load Balancer, Tanzu Observability, Tanzu Service Mesh. 
Exception - Tables and figures. TKG, TMC, NSX ALB, TO, TSM.

2022-06-10 21:35 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Once the Edge site is deployed, Tanzu Mission Control is used for fleet management, allowing an easy way to manage and lifecycle TKG workload clusters at the edge.
Once the edge site is ... Tanzu Kubernetes Grid workload ...

2022-06-10 21:36 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +- Limited recoverability when site is disconnected
Add period.

2022-06-10 21:37 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +![](./img/tkg-edge/tkg-edge-hub-spoke.drawio.png)
Add text in square brackets. Possible text: Hub and spoke topology.

2022-06-10 21:38 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +In this topology, only the TKG Management cluster is located in a central location.
... Tanzu Kubernetes Grid management cluster ...

2022-06-10 21:42 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Each Edge site has the infrastructure management plane (vCenter, and NSX Advanced Load Balancer controllers, DNS servers and NTP server). This design provides a better availability when the edge loca
Each edge site contains the infrastructure management plane, which includes vCenter, NSX Advanced Load Balancer Controllers, DNS servers, and NTP servers. This design provides better availability ...

2022-06-10 21:44 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Some additional components for monitoring, backup and log management could be also installed at the Edge location to provide these functions locally.
Additional component for monitoring, backup, and log management can also be installed at the edge location to provide the functionality locally.

2022-06-10 21:44 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +![](./img/tkg-edge/tkg-edge-hybrid.drawio.png)
Suggested text to add in square brackets - Hybrid topology

2022-06-14 01:24 UTC, srinivasme21 requested changes
Global: Please replace screen captures with light background

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +For companies modernizing their application estate, it is not uncommon to have cloud native deployments across many locations. They will run Kubernetes clusters in their core data centers (in the 10s
You will run Kubernetes clusters in your core data centers (in the 10s), mini data centers away from the core data center (in the 100s), and thousands of smaller 2 to 3 server deployments at locations like stores, similar to this design. To manage this vast Kubernetes estate at scale, you need a centralized control plane that can help you deploy, manage, secure, and provide insights into your Kubernetes deployments.

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +TMC is a centralized management platform for consistently operating and securing your Kubernetes infrastructure and modern applications across multiple teams and clouds. It can manage and ensure oper
Tanzu Mission Control is a centralized ... consistently with the following capabilities:

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +With TMC you can group clusters based on different types of locations and manage fleets of clusters instead of managing them individually. When we are dealing with large scale edge deployments this b
With Tanzu Mission Control ... The following figure shows an overview ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure: Managing the edge cluster fleet using TMC
Move the figure caption into the square brackets.

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +#### Policy Management example
Example

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Policies allow you to provide a set of rules that govern your organization and all the objects it contains. Policies can be applied to fleets of clusters by defining once to ensure that the kubernete
Policies allow ... ensure that the Kubernetes clusters and ... Tanzu Mission Control provides ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure X and Figure X below showcase how customers can create policies and use the policy insights page to review if any of the policies are violated across all the edge deployments.
The following figures showcase how customers ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +#### Usage consideration
Considerations

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +As of time of writing [Tanzu Mission Control][701] requires,  at least, ~1.5GB of memory and ~1 vCPU per managed cluster to operate.
Tanzu Mission Control requires, at least, ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure: Using TMC to manage edge cluster policies
Move figure caption into the square brackets.

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Figure: Policy reporting across all edge locations
Move figure caption into the square brackets.

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +
The following table describes the resources used by Tanzu Mission Control components.

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +## Monitoring, Logging and Observability
... Logging, and ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +TKG also supports Grafana and Prometheus as alternative on premise solutions that can be used for monitoring.
Tanzu Kubernetes Grid ... as alternative on premises solutions ...

2022-06-14 01:24 UTC, srinivasme21 commented on src/reference-designs/tkg-edge.md
> +Fluent Bit is particularly well suited for Edge use case with its [buffering][802] capability that can be used to retain logs until the main datacenter reconnect.
... for an edge use case ... reconnects.

2022-06-14 01:24 UTC, srinivasme21 requested changes
Global: Please replace screen captures with light background

2022-06-14 01:25 UTC, srinivasme21 requested changes
Global: Please replace screen captures with light background

2022-06-30 07:36 UTC, bserratrice commented
> Global: Please replace screen captures with light background

The lab environment is not available anymore, I'll this in mind for the next major release.

2022-07-14 19:00 UTC, merged