171 tanzu service mesh workload cluster sizing
vmware-tanzu-labs/tanzu-validated-solutions pull request #177
Opened 2022-04-29 19:29 UTC by itgrl-bex

Added small note to the Tanzu Service Mesh section regarding workload cluster sizing with link to the TSM requirements doc.

This PR addresses Issue 171

Signed by: rerobinson@vmware.com

2022-06-14 04:15 UTC, manishjha86 approved these changes

2022-06-27 16:34 UTC, srinivasme21 commented on src/deployment-guides/tko-saas-services.md
> +* Workload cluster resource requirements: *Please see [TSM requirements](https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/services/tanzu-service-mesh-environment-requirements-and-supported-platfo
...: For workload cluster resource requirements, see [Tanzu Service Mesh Environment Requirements and Supported Platforms] (https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/services/tanzu-service-mesh-environment-requirements-and-supported-platforms/GUID-D0B939BE-474E-4075-9A65-3D72B5B9F237.html)

2022-06-27 16:53 UTC, srinivasme21 commented on src/deployment-guides/tko-saas-services.md
> +   - If using user managed packages such as cert-manager, contour, prometheus, and grafana, you will want to exclude those namespaces.
If you install user-managed packages such as Cert Manager, Contour, Prometheus, and Grafana, exclude the related namespaces for the user-managed packages:

2022-06-27 16:54 UTC, srinivasme21 commented on src/deployment-guides/tko-saas-services.md
>  6. On the target cluster, you will see a new namespace vmware-system-tsm and required objects being created. When all the required Kubernetes objects are created and are in a running state, status of
Does not need to be separate step. This can be a paragraph under the step 5.

2022-06-27 16:55 UTC, srinivasme21 requested changes
Change the screen capture to light background. 

Please update with the comments.

2022-08-01 17:34 UTC, srinivasme21 approved these changes
LGTM

2022-08-01 21:11 UTC, merged