Adding tko-saas-deploy-guide 2.0
vmware-tanzu-labs/tanzu-validated-solutions pull request #193
Opened 2022-05-12 04:49 UTC by manishjha86

Signed-off-by: Manish Jha <er.manish.jha@gmail.com>

2022-06-07 02:27 UTC, craigtracey requested changes

2022-06-07 02:27 UTC, craigtracey commented on wordlist.txt
> +configproxy
Remove this please.

2022-06-07 02:27 UTC, craigtracey commented on src/deployment-guides/tko-saas-services.md
> +  ### <a id=configproxy> </a>Supplemental Information: Create a Proxy Configuration Object in Tanzu Mission Control
Please make this `<a id="configproxy">`

2022-06-07 02:27 UTC, craigtracey commented on src/deployment-guides/tko-saas-services.md
> +	     <!-- /* cSpell:disable */ -->
Please remove this cSpell annotation

2022-06-07 02:27 UTC, craigtracey commented on src/deployment-guides/tko-saas-services.md
> +	    <!-- /* cSpell:enable */ -->
Please remove this cSpell annotation

2022-06-09 21:57 UTC, srinivasme21 approved these changes
IX review provided and merged.

2022-06-10 12:44 UTC, craigtracey approved these changes

2022-06-10 12:44 UTC, merged