Adding tko-vwt-dg 2.0
vmware-tanzu-labs/tanzu-validated-solutions pull request #194
Opened 2022-05-12 07:59 UTC by manishjha86

Signed-off-by: Manish Jha <er.manish.jha@gmail.com>

2022-05-26 16:33 UTC, MarilynHorn commented on src/deployment-guides/tko-on-vsphere-with-tanzu.md
> +   If you did not select the **Setup Cloud After** option <_I don't see this option_> before saving, the initial configuration wizard exits. The Cloud configuration window does not automatically laun
```suggestion
   If you did not select the **Setup Cloud After** option before saving, the initial configuration wizard ends. The cloud configuration window does not automatically launch and you are directed to a dashboard view on the controller.
```

2022-05-26 17:12 UTC, MarilynHorn requested changes
Overall, looks good. I removed one embedded comment at line 143 and added it as a comment here.

2022-05-26 17:12 UTC, MarilynHorn commented on src/deployment-guides/tko-on-vsphere-with-tanzu.md
> +   If you did not select the **Setup Cloud After** option <_I don't see this option_> before saving, the initial configuration wizard exits. The Cloud configuration window does not automatically laun
I removed my embedded comment **<_I don't see that option_>** from the MD file so I could explain it here, which is a better place for comments. When I reviewed this guide, I didn't see where the **Setup Cloud After** option is.  Was it shown in one of the screenshots you replaced, or did I just miss it? Please verify that the option is still in the wizard, and if it is, consider rewording this line so it's clearer.

2022-06-09 21:56 UTC, srinivasme21 approved these changes
LGTM.

2022-06-10 13:02 UTC, craigtracey approved these changes

2022-06-10 13:10 UTC, merged