Added note about using cluster.local for serviceDomain. Added info ab…
vmware-tanzu-labs/tanzu-validated-solutions pull request #247
Opened 2022-08-03 18:39 UTC by itgrl-bex

…out adding kapp-controller and secretgen-controller when using TKGs and deploying clusters via yaml files.

Signed-off-by: itgrl-bex <rerobinson@vmware.com>

2022-08-04 18:00 UTC, srinivasme21 requested changes
Please review and incorporate the comments.

2022-08-04 18:05 UTC, itgrl-bex commented on src/deployment-guides/tap.md
> +<!-- /* cSpell:disable */ -->
Yes, they are.  cSpell was failing on secretgen

2022-08-05 18:30 UTC, srinivasme21 approved these changes
LGTM

2022-08-24 20:32 UTC, craigtracey approved these changes

2022-08-24 20:32 UTC, merged