Created dedicated md file for TKO SaaS contents for RA
vmware-tanzu-labs/tanzu-validated-solutions pull request #63
Opened 2022-02-04 06:14 UTC by manishjha86

Created dedicated md file for TKO SaaS contents for RA

2022-02-08 18:03 UTC, craigtracey commented
HI @manishjha86 please take a look at the CLA requirements above as that will be necessary before merge. Thanks.

2022-03-10 17:42 UTC, craigtracey requested changes
I have made a few suggestions that I believe should be addressed. 

Additionally, this change has broken tests that will need to be addressed. First the broken link check is failing on `toc.md` as the file has been renamed. The orphaned file check is failing because we now have image files that are not being referenced any longer. Those files will need to be deleted.

To verify that your changes have fixed testing, please run `act` locally as described in [TESTING](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/TESTING.md#running-tests)

2022-03-10 17:42 UTC, craigtracey commented on src/reference-designs/tko-saas.md
> +VMware recommends that you attach the shared services and workload clusters into Tanzu Mission Control as it provides a centralized administrative interface that enables you to manage your global por
```suggestion
VMware recommends that you attach the shared services and workload clusters into Tanzu Mission Control as it provides a centralized administrative interface that enables you to manage your global portfolio of Kubernetes clusters. If the Tanzu Kubernetes Grid clusters are behind a proxy, import your proxy configuration to Tanzu Mission Control and then attach the cluster using Tanzu Mission Control UI or CLI.
```

2022-03-10 17:42 UTC, craigtracey commented on src/reference-designs/tko-saas.md
> +The SaaS products in the VMware Tanzu portfolio are in the critical path for securing systems at the heart of your IT infrastructure. VMware Tanzu Mission Control provides a centralized control plane
```suggestion
The SaaS products in the VMware Tanzu portfolio are critical components for securing your IT infrastructure. VMware Tanzu Mission Control provides a centralized control plane for Kubernetes, and Tanzu Service Mesh provides a global control plane for service mesh networks. VMware Tanzu Observability by Wavefront offers observability and analytics for multi-cloud Kubernetes environments.
```

2022-03-10 17:42 UTC, craigtracey commented on src/reference-designs/tko-saas.md
> +# Tanzu for Kubernetes Operation SaaS Integration
```suggestion
# Tanzu for Kubernetes Operations SaaS Integration
```

2022-03-10 17:42 UTC, craigtracey commented on src/reference-designs/tko-saas.md
> +**Note:** Registering Tanzu Kubernetes Grid 1.4 management cluster to Tanzu Mission Control is not supported.
```suggestion
**Note:** Registering Tanzu Kubernetes Grid 1.4 management clusters to Tanzu Mission Control is not supported.
```

2022-03-10 18:01 UTC, craigtracey commented
@srinivasme21 please take a look for IX. Specifically, for how this will affect the TOC,

2022-03-16 00:21 UTC, MarilynHorn requested changes
This diagram in
**TSM-App-Connectivity.png**  will be VERY difficult to read, even if enlarged to fill the screen. It would be more legible if you redo it with the following changes:

1) If possible, change the application used to create  to a **light** theme and reshoot it. Most recent applications let you choose a color theme, and for some reason I don't understand, default to a dark theme. It's ALWAYS harder to read light text against a dark background than dark text against a light background. (There has been a lot of research about this.)

2) When you re-do the screen capture, capture just the part of the screen that's relevant. You probably don't need the sidebar on the left, much of the text above the diagram, and the black space below the diagram. On Windows, use the Snipping Tool to capture a rectangle.
On a Mac, press **Shift**, **Command**, and **4** to capture a rectangular area.

3) If you can make the text in the diagram larger before you capture the screen, that would be a big help.

2022-03-16 18:27 UTC, craigtracey commented
@manishjha86 @srinivasme21 bump

2022-03-17 11:40 UTC, MarilynHorn requested changes
The only md file that requires changes is 'tko-saas.md'. Most of my suggestions are to conform more closely to the VMware writing guidelines.

The following 3 png files should be redone so that they are easier to read:

'TSM-APP-CONNECTIVITY.PNG'
'TSM-OBSERVABILITY.PNG'
'TSM-RESILIANCY.PNG'

Here are suggestions for making the graphics easier to read:

1. If possible, change to a light theme and recapture. It's much easier to read dark text against a light background than light text against a dark background. (There has been a lot of research about this.)
1. Before capturing the screen, make the text larger.
1. Capture just the part of the screen that's relevant. You probably don't need the sidebar on the left, much of the text above the diagram, and the black space below the diagram. On Windows, use the Snipping Tool to capture a rectangle.  On a Mac, press **Shift**, **Command**, and **4** to capture a rectangular area. Alternatively, you can capture the full screen and use a graphics editor to crop it.

2022-03-29 20:58 UTC, craigtracey approved these changes

2022-03-29 20:58 UTC, merged